{
  "formatVersion": "1.1",
  "component": {
    "group": "com.messiahofdoom",
    "module": "DoomedLib-Fabric",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DoomedLib-Fabric-0.9.0.jar",
          "url": "DoomedLib-Fabric-0.9.0.jar",
          "size": 260786,
          "sha512": "6ede03aba68c7462fd67681eaa3571e715e6510f4964464468728d1e320201030bd8c949a5a5fe7da160c5f103833929f3d08e1c1bdc2698a3e27f5e889a7fb4",
          "sha256": "3917c83ae6a9cf28e58c52be255c4712c5df2dad1703c848d03c79b3d2c433c3",
          "sha1": "01003f8b72c34055c99a3d408990e35bc3bb80d2",
          "md5": "d9732f75fe8c1957565d2d06456b31d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.47.8+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "DoomedLib-Fabric-0.9.0.jar",
          "url": "DoomedLib-Fabric-0.9.0.jar",
          "size": 260786,
          "sha512": "6ede03aba68c7462fd67681eaa3571e715e6510f4964464468728d1e320201030bd8c949a5a5fe7da160c5f103833929f3d08e1c1bdc2698a3e27f5e889a7fb4",
          "sha256": "3917c83ae6a9cf28e58c52be255c4712c5df2dad1703c848d03c79b3d2c433c3",
          "sha1": "01003f8b72c34055c99a3d408990e35bc3bb80d2",
          "md5": "d9732f75fe8c1957565d2d06456b31d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DoomedLib-Fabric-0.9.0-sources.jar",
          "url": "DoomedLib-Fabric-0.9.0-sources.jar",
          "size": 232068,
          "sha512": "ba51ba6ff342f54a95b2b05b210cde7200bb08909b72e2eff9b18edfafde12ac1b578dfb8c641eeaf63d12e76c6d4913dcdc274c75b6375b167aadc2ccb845a7",
          "sha256": "9b5d18c2e5bc72330ae68077a437bad52bae7e062f6f6d3c55d3b226249cfaeb",
          "sha1": "989a8f287815217d3d7403656d2d596465b46e89",
          "md5": "e882c4f8f55f9acd6d45ed3e83069c5c"
        }
      ]
    }
  ]
}
